### ISSUE TITLE
Tab Content Not Changing Dynamically

### ISSUE THREAD

**Issue by RailsCod3rFuture** [resivalex/rails-bootstrap-tabs#2]
When I add ruby oriented code to the tab bodies. Only the first tab shows the dynamic content, but none of the other tabs work when I try to switch to them. How do I address this issue with your approach??

```
<%= tabs fade_effect: true do |c| %>
            <% c.tab "Movies (#{@user.movies.count})" do %>
              <% @movies.each do |mov| %>
              <%= mov.title %>
              <% end %>
            <% end %>
            <% c.tab "Reviews (#{@user.movie_reviews.count})" do %>
            <% end %>
            <% c.tab "Post (#{@user.posts.count})" do %>
            <% @posts.each do |post| %>
             <%= post.title %>
             <%= post.body %>
             <% end %>
            <% end %>
          <% end %>
```

**Comment by resivalex** [comment]
What do you mean by "dynamic content"?
Don't tab switch, does selected tab reset to the first tab on re-render?
Give more details, please.

**Comment by RailsCod3rFuture** [comment]
When the page loads, the first tab content shows, but I cannot switch to another tab's content. Almost like you're clicking on the tab button but no response is returned. I simply need the tab content to render when I'm changing each particular tab view. Post tab -> show posts, Movies tab -> show movies, in real-time.

**Comment by resivalex** [comment]
You can set `active: true` option for a tab, which should be shown after page renders.
If you want to change the tabs content without reloading the page, you can re-render these tab with the help of JS, making request to server by AJAX.
Are you sure, that tab click is the right event to refresh content?

**Comment by RailsCod3rFuture** [comment]
Yeah, its an AJAX issue. Do you know how to refresh each tab with AJAX to get the results that I want, using the anchor: tag??

**Comment by RailsCod3rFuture** [comment]
I will see if someone on Stackoverflow has an approach. I'll just show them the template and render code that you gave with your gem.

**Comment by resivalex** [comment]
I would make something like

index.html.erb
```
<div id="dynamic_content">
  <%= render 'dynamic_content', selected_tab: @selected_tab_eg_from_parameters %>
</div>
```

_dynamic_content.erb.html
```
<%= tabs fade_effect: true do |c| %>
  <% c.tab "Movies (#{@user.movies.count})", active: (selected_tab == 'movies') do %>
    <% @movies.each do |mov| %>
    <%= mov.title %>
    <% end %>
  <% end %>
  <% c.tab "Reviews (#{@user.movie_reviews.count})", active: (selected_tab == 'reviews') do %>
  <% end %>
  <% c.tab "Post (#{@user.posts.count})", active: (selected_tab == 'posts') do %>
  <% @posts.each do |post| %>
   <%= post.title %>
   <%= post.body %>
   <% end %>
  <% end %>
<% end %>
```

JS
```
setInterval(function() {
  // There is a problem how to get currently selected tab
  $.get(...).success(function(response) {
    $('#dynamic_content').html(response.body);
  }),
  5000
)
```

**Comment by RailsCod3rFuture** [comment]
Thanks bro, I'll try to work with it.

**Comment by resivalex** [comment]
This gem lacks a mechanism to act with tabs dynamically by JS. It's useful for adding sections with tabs along a static page.
