### ISSUE TITLE
Support nav markup

### ISSUE THREAD

**Issue by renatomolina** [resivalex/rails-bootstrap-tabs#5]
[According to bootstrap](https://getbootstrap.com/docs/5.0/components/navs-tabs/), you can also use nav markup to make navbar instead of `ul` and `li`.

`navs` are more accessibility friendly than `ul` `li` for screenreaders, I think this is a worthy feature to consider.
https://www.w3schools.com/tags/tag_nav.asp
https://css-tricks.com/navigation-in-lists-to-be-or-not-to-be/

**Comment by resivalex** [comment]
@renatomolina, thanks for the issue. I'll try to implement it this week

**Comment by renatomolina** [comment]
actually I'm working on that if you don't mind @resivalex

**Comment by resivalex** [comment]
@renatomolina Cool! Pull requests are welcome

**Comment by renatomolina** [comment]
done: https://github.com/resivalex/rails-bootstrap-tabs/pull/7

Thanks in advanced for the review

**Comment by resivalex** [comment]
Version 0.2.7 is published
