### ISSUE TITLE
Bootstrap 5?

### ISSUE THREAD

**Issue by markmcdonald51** [resivalex/rails-bootstrap-tabs#8]
Hi!

This is one of the niftiest gems I have used for bootstrap tabs, which obviously you saw that they can be a pain in an azz to set up correctly. I have switched over to rails 7 which now uses Bootstrap 5 and it looks as though it has broken your gem. I am not much for content_tag development like you, but I am thinking I may try to get this working with BS5 as there are some really nice new features with tabs.  Anyway, thanks so much for making this gem public and if you have any inclination to get it working with BS5 lemme know! This really is a great gem!

**Comment by resivalex** [comment]
Hi @markmcdonald51!
Thank you for the feedback! I'll see into the issue over the weekend.

**Comment by resivalex** [comment]
**Bootstrap 5** is available since **0.3.1** version.
